2023-12-07T00:34:03.0461978Z ##[group]Run actions/setup-python@v4
2023-12-07T00:34:03.0462551Z with:
2023-12-07T00:34:03.0462879Z   python-version: 3.8
2023-12-07T00:34:03.0463277Z   architecture: x64
2023-12-07T00:34:03.0463694Z   cache: pip
2023-12-07T00:34:03.0463996Z   check-latest: false
2023-12-07T00:34:03.0464538Z   token: ***
2023-12-07T00:34:03.0464950Z   update-environment: true
2023-12-07T00:34:03.0465400Z   allow-prereleases: false
2023-12-07T00:34:03.0465744Z ##[endgroup]
2023-12-07T00:34:03.1855474Z ##[group]Installed versions
2023-12-07T00:34:03.1934345Z Successfully set up CPython (3.8.18)
2023-12-07T00:34:03.1935733Z ##[endgroup]
2023-12-07T00:34:04.0773538Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-12-07T00:34:04.4284222Z /home/runner/.cache/pip
2023-12-07T00:34:04.7598887Z Received 6245959 of 6245959 (100.0%), 38.2 MBs/sec
2023-12-07T00:34:04.7600071Z Cache Size: ~6 MB (6245959 B)
2023-12-07T00:34:04.7630689Z [command]/usr/bin/tar -xf /home/runner/work/_temp/d36098a2-96b6-43dc-93dd-1324c2ef16c9/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-12-07T00:34:04.7915447Z Cache restored successfully
2023-12-07T00:34:04.7937142Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
