2023-02-23T01:49:06.0046094Z ##[group]Run actions/setup-python@v4
2023-02-23T01:49:06.0046442Z with:
2023-02-23T01:49:06.0046705Z   python-version: 3.8
2023-02-23T01:49:06.0047013Z   architecture: x64
2023-02-23T01:49:06.0047301Z   cache: pip
2023-02-23T01:49:06.0047580Z   check-latest: false
2023-02-23T01:49:06.0048087Z   token: ***
2023-02-23T01:49:06.0048395Z   update-environment: true
2023-02-23T01:49:06.0048698Z ##[endgroup]
2023-02-23T01:49:06.1751440Z ##[group]Installed versions
2023-02-23T01:49:06.1839657Z Successfully set up CPython (3.8.16)
2023-02-23T01:49:06.1840687Z ##[endgroup]
2023-02-23T01:49:06.5946445Z [command]/opt/hostedtoolcache/Python/3.8.16/x64/bin/pip cache dir
2023-02-23T01:49:06.9800865Z /home/runner/.cache/pip
2023-02-23T01:49:07.2707918Z pip cache is not found
