2023-04-04T01:39:52.9983903Z ##[group]Run actions/setup-python@v4
2023-04-04T01:39:52.9984181Z with:
2023-04-04T01:39:52.9984456Z   python-version: 3.8
2023-04-04T01:39:52.9984671Z   architecture: x64
2023-04-04T01:39:52.9984868Z   cache: pip
2023-04-04T01:39:52.9985055Z   check-latest: false
2023-04-04T01:39:52.9985446Z   token: ***
2023-04-04T01:39:52.9985652Z   update-environment: true
2023-04-04T01:39:52.9985860Z ##[endgroup]
2023-04-04T01:39:53.1686785Z ##[group]Installed versions
2023-04-04T01:39:53.1770438Z Successfully set up CPython (3.8.16)
2023-04-04T01:39:53.1771208Z ##[endgroup]
2023-04-04T01:39:53.6648816Z [command]/opt/hostedtoolcache/Python/3.8.16/x64/bin/pip cache dir
2023-04-04T01:39:54.0581782Z /home/runner/.cache/pip
2023-04-04T01:39:54.5001973Z Received 6243437 of 6243437 (100.0%), 38.2 MBs/sec
2023-04-04T01:39:54.5002637Z Cache Size: ~6 MB (6243437 B)
2023-04-04T01:39:54.5026466Z [command]/usr/bin/tar -z -xf /home/runner/work/_temp/a04e5581-f14d-4885-a56f-c12628f6648a/cache.tgz -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A
2023-04-04T01:39:54.5634307Z Cache restored successfully
2023-04-04T01:39:54.5650131Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.16-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
