2023-09-26T00:22:16.3158403Z ##[group]Run actions/setup-python@v4
2023-09-26T00:22:16.3158780Z with:
2023-09-26T00:22:16.3159032Z   python-version: 3.8
2023-09-26T00:22:16.3159480Z   architecture: x64
2023-09-26T00:22:16.3159795Z   cache: pip
2023-09-26T00:22:16.3160095Z   check-latest: false
2023-09-26T00:22:16.3160505Z   token: ***
2023-09-26T00:22:16.3160874Z   update-environment: true
2023-09-26T00:22:16.3161216Z   allow-prereleases: false
2023-09-26T00:22:16.3161542Z ##[endgroup]
2023-09-26T00:22:16.4933632Z ##[group]Installed versions
2023-09-26T00:22:16.5020437Z Successfully set up CPython (3.8.18)
2023-09-26T00:22:16.5021590Z ##[endgroup]
2023-09-26T00:22:17.3376438Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-09-26T00:22:20.1113169Z /home/runner/.cache/pip
2023-09-26T00:22:20.4007301Z Received 6245959 of 6245959 (100.0%), 48.4 MBs/sec
2023-09-26T00:22:20.4008267Z Cache Size: ~6 MB (6245959 B)
2023-09-26T00:22:20.4037643Z [command]/usr/bin/tar -xf /home/runner/work/_temp/91f2f727-f717-418f-bd27-58359d1a6ee3/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-09-26T00:22:20.4272083Z Cache restored successfully
2023-09-26T00:22:20.4290865Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
