2023-09-17T00:23:52.8417110Z ##[group]Run actions/setup-python@v4
2023-09-17T00:23:52.8417378Z with:
2023-09-17T00:23:52.8417583Z   python-version: 3.8
2023-09-17T00:23:52.8417814Z   architecture: x64
2023-09-17T00:23:52.8418038Z   cache: pip
2023-09-17T00:23:52.8418245Z   check-latest: false
2023-09-17T00:23:52.8418631Z   token: ***
2023-09-17T00:23:52.8418836Z   update-environment: true
2023-09-17T00:23:52.8419071Z   allow-prereleases: false
2023-09-17T00:23:52.8419283Z ##[endgroup]
2023-09-17T00:23:53.0241062Z ##[group]Installed versions
2023-09-17T00:23:53.0340702Z Successfully set up CPython (3.8.18)
2023-09-17T00:23:53.0341340Z ##[endgroup]
2023-09-17T00:23:53.8332560Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-09-17T00:23:56.0346032Z /home/runner/.cache/pip
2023-09-17T00:23:56.7757382Z Received 6245959 of 6245959 (100.0%), 15.2 MBs/sec
2023-09-17T00:23:56.7758337Z Cache Size: ~6 MB (6245959 B)
2023-09-17T00:23:56.7790081Z [command]/usr/bin/tar -xf /home/runner/work/_temp/167992b5-9596-493f-a5ff-747b607c536f/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-09-17T00:23:56.8155990Z Cache restored successfully
2023-09-17T00:23:56.8174537Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
