2023-12-05T00:24:45.5302977Z ##[group]Run actions/setup-python@v4
2023-12-05T00:24:45.5303479Z with:
2023-12-05T00:24:45.5304179Z   python-version: 3.8
2023-12-05T00:24:45.5304534Z   architecture: x64
2023-12-05T00:24:45.5304898Z   cache: pip
2023-12-05T00:24:45.5305291Z   check-latest: false
2023-12-05T00:24:45.5305822Z   token: ***
2023-12-05T00:24:45.5306164Z   update-environment: true
2023-12-05T00:24:45.5306635Z   allow-prereleases: false
2023-12-05T00:24:45.5307015Z ##[endgroup]
2023-12-05T00:24:45.6680631Z ##[group]Installed versions
2023-12-05T00:24:45.6755982Z Successfully set up CPython (3.8.18)
2023-12-05T00:24:45.6757762Z ##[endgroup]
2023-12-05T00:24:46.5665394Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-12-05T00:24:46.8993035Z /home/runner/.cache/pip
2023-12-05T00:24:47.3257416Z Received 6245959 of 6245959 (100.0%), 37.5 MBs/sec
2023-12-05T00:24:47.3258425Z Cache Size: ~6 MB (6245959 B)
2023-12-05T00:24:47.3285661Z [command]/usr/bin/tar -xf /home/runner/work/_temp/a2acdcd2-f909-44f9-904d-1eb63898d343/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-12-05T00:24:47.3556793Z Cache restored successfully
2023-12-05T00:24:47.3576499Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
