2024-02-04T00:25:06.4568296Z ##[group]Run actions/setup-python@v4
2024-02-04T00:25:06.4568767Z with:
2024-02-04T00:25:06.4569153Z   python-version: 3.8
2024-02-04T00:25:06.4569526Z   architecture: x64
2024-02-04T00:25:06.4569863Z   cache: pip
2024-02-04T00:25:06.4570264Z   check-latest: false
2024-02-04T00:25:06.4570733Z   token: ***
2024-02-04T00:25:06.4571067Z   update-environment: true
2024-02-04T00:25:06.4571535Z   allow-prereleases: false
2024-02-04T00:25:06.4571886Z ##[endgroup]
2024-02-04T00:25:06.5962201Z ##[group]Installed versions
2024-02-04T00:25:06.6039253Z Successfully set up CPython (3.8.18)
2024-02-04T00:25:06.6040771Z ##[endgroup]
2024-02-04T00:25:07.5747596Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2024-02-04T00:25:11.3100092Z /home/runner/.cache/pip
2024-02-04T00:25:11.5703758Z Received 6245959 of 6245959 (100.0%), 56.2 MBs/sec
2024-02-04T00:25:11.5704982Z Cache Size: ~6 MB (6245959 B)
2024-02-04T00:25:11.5733285Z [command]/usr/bin/tar -xf /home/runner/work/_temp/954c53e5-10f0-40bb-b6cd-5df7dcf0a0cd/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2024-02-04T00:25:11.6005009Z Cache restored successfully
2024-02-04T00:25:11.6026161Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
