2023-11-18T00:23:46.1411462Z ##[group]Run actions/setup-python@v4
2023-11-18T00:23:46.1412052Z with:
2023-11-18T00:23:46.1412353Z   python-version: 3.8
2023-11-18T00:23:46.1412801Z   architecture: x64
2023-11-18T00:23:46.1413225Z   cache: pip
2023-11-18T00:23:46.1413511Z   check-latest: false
2023-11-18T00:23:46.1414007Z   token: ***
2023-11-18T00:23:46.1414432Z   update-environment: true
2023-11-18T00:23:46.1414826Z   allow-prereleases: false
2023-11-18T00:23:46.1415164Z ##[endgroup]
2023-11-18T00:23:46.2764565Z ##[group]Installed versions
2023-11-18T00:23:46.2838643Z Successfully set up CPython (3.8.18)
2023-11-18T00:23:46.2840056Z ##[endgroup]
2023-11-18T00:23:47.1398772Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-11-18T00:23:47.5423582Z /home/runner/.cache/pip
2023-11-18T00:23:47.8766256Z Received 6245959 of 6245959 (100.0%), 43.8 MBs/sec
2023-11-18T00:23:47.8767299Z Cache Size: ~6 MB (6245959 B)
2023-11-18T00:23:47.8794142Z [command]/usr/bin/tar -xf /home/runner/work/_temp/ffb34328-74c5-441c-b59a-81292c2574ba/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-11-18T00:23:47.9072596Z Cache restored successfully
2023-11-18T00:23:47.9092552Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
