2024-01-04T00:24:18.3162495Z ##[group]Run actions/setup-python@v4
2024-01-04T00:24:18.3162972Z with:
2024-01-04T00:24:18.3163396Z   python-version: 3.8
2024-01-04T00:24:18.3163796Z   architecture: x64
2024-01-04T00:24:18.3164484Z   cache: pip
2024-01-04T00:24:18.3164920Z   check-latest: false
2024-01-04T00:24:18.3165465Z   token: ***
2024-01-04T00:24:18.3165902Z   update-environment: true
2024-01-04T00:24:18.3166263Z   allow-prereleases: false
2024-01-04T00:24:18.3166644Z ##[endgroup]
2024-01-04T00:24:18.4508575Z ##[group]Installed versions
2024-01-04T00:24:18.4585631Z Successfully set up CPython (3.8.18)
2024-01-04T00:24:18.4587160Z ##[endgroup]
2024-01-04T00:24:19.4295839Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2024-01-04T00:24:24.2034510Z /home/runner/.cache/pip
2024-01-04T00:24:24.5947630Z Received 6245959 of 6245959 (100.0%), 37.9 MBs/sec
2024-01-04T00:24:24.5948698Z Cache Size: ~6 MB (6245959 B)
2024-01-04T00:24:24.5979716Z [command]/usr/bin/tar -xf /home/runner/work/_temp/50779047-c5e1-4b39-b35d-4d06126fb00e/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2024-01-04T00:24:24.6399681Z Cache restored successfully
2024-01-04T00:24:24.6421455Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
