2024-01-13T00:24:18.0293958Z ##[group]Run actions/setup-python@v4
2024-01-13T00:24:18.0294560Z with:
2024-01-13T00:24:18.0294847Z   python-version: 3.8
2024-01-13T00:24:18.0295220Z   architecture: x64
2024-01-13T00:24:18.0295644Z   cache: pip
2024-01-13T00:24:18.0295971Z   check-latest: false
2024-01-13T00:24:18.0296497Z   token: ***
2024-01-13T00:24:18.0296866Z   update-environment: true
2024-01-13T00:24:18.0297244Z   allow-prereleases: false
2024-01-13T00:24:18.0297610Z ##[endgroup]
2024-01-13T00:24:18.1654288Z ##[group]Installed versions
2024-01-13T00:24:18.1725981Z Successfully set up CPython (3.8.18)
2024-01-13T00:24:18.1727599Z ##[endgroup]
2024-01-13T00:24:19.1124419Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2024-01-13T00:24:19.4548614Z /home/runner/.cache/pip
2024-01-13T00:24:19.7230031Z Received 6245959 of 6245959 (100.0%), 54.2 MBs/sec
2024-01-13T00:24:19.7231035Z Cache Size: ~6 MB (6245959 B)
2024-01-13T00:24:19.7259851Z [command]/usr/bin/tar -xf /home/runner/work/_temp/d81a70f9-14a6-4fbf-b143-596c6607c84a/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2024-01-13T00:24:19.7527130Z Cache restored successfully
2024-01-13T00:24:19.7548637Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
