2023-10-06T00:22:39.1568985Z ##[group]Run actions/setup-python@v4
2023-10-06T00:22:39.1569235Z with:
2023-10-06T00:22:39.1569438Z   python-version: 3.8
2023-10-06T00:22:39.1569657Z   architecture: x64
2023-10-06T00:22:39.1569854Z   cache: pip
2023-10-06T00:22:39.1570052Z   check-latest: false
2023-10-06T00:22:39.1570386Z   token: ***
2023-10-06T00:22:39.1570587Z   update-environment: true
2023-10-06T00:22:39.1570823Z   allow-prereleases: false
2023-10-06T00:22:39.1571029Z ##[endgroup]
2023-10-06T00:22:39.3401538Z ##[group]Installed versions
2023-10-06T00:22:39.3452178Z Successfully set up CPython (3.8.18)
2023-10-06T00:22:39.3452796Z ##[endgroup]
2023-10-06T00:22:40.1103893Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-10-06T00:22:40.4811377Z /home/runner/.cache/pip
2023-10-06T00:22:40.8354067Z Received 6245959 of 6245959 (100.0%), 35.7 MBs/sec
2023-10-06T00:22:40.8354782Z Cache Size: ~6 MB (6245959 B)
2023-10-06T00:22:40.8382295Z [command]/usr/bin/tar -xf /home/runner/work/_temp/3b26dc6d-d038-4d53-963b-d169c0411762/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-10-06T00:22:40.8608163Z Cache restored successfully
2023-10-06T00:22:40.8625368Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
