2023-09-19T00:22:34.7378662Z ##[group]Run actions/setup-python@v4
2023-09-19T00:22:34.7379052Z with:
2023-09-19T00:22:34.7379398Z   python-version: 3.8
2023-09-19T00:22:34.7379740Z   architecture: x64
2023-09-19T00:22:34.7380044Z   cache: pip
2023-09-19T00:22:34.7380362Z   check-latest: false
2023-09-19T00:22:34.7381006Z   token: ***
2023-09-19T00:22:34.7381277Z   update-environment: true
2023-09-19T00:22:34.7381622Z   allow-prereleases: false
2023-09-19T00:22:34.7381945Z ##[endgroup]
2023-09-19T00:22:34.9213496Z ##[group]Installed versions
2023-09-19T00:22:34.9303776Z Successfully set up CPython (3.8.18)
2023-09-19T00:22:34.9304847Z ##[endgroup]
2023-09-19T00:22:35.7965621Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-09-19T00:22:36.2552273Z /home/runner/.cache/pip
2023-09-19T00:22:37.3351214Z Received 6245959 of 6245959 (100.0%), 9.2 MBs/sec
2023-09-19T00:22:37.3352990Z Cache Size: ~6 MB (6245959 B)
2023-09-19T00:22:37.3382129Z [command]/usr/bin/tar -xf /home/runner/work/_temp/aaead529-442d-4865-ade4-a3ef4d42e965/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-09-19T00:22:37.3642437Z Cache restored successfully
2023-09-19T00:22:37.3660632Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
