2023-10-11T00:22:37.9494812Z ##[group]Run actions/setup-python@v4
2023-10-11T00:22:37.9495366Z with:
2023-10-11T00:22:37.9495739Z   python-version: 3.8
2023-10-11T00:22:37.9496074Z   architecture: x64
2023-10-11T00:22:37.9496427Z   cache: pip
2023-10-11T00:22:37.9496852Z   check-latest: false
2023-10-11T00:22:37.9497408Z   token: ***
2023-10-11T00:22:37.9497724Z   update-environment: true
2023-10-11T00:22:37.9498128Z   allow-prereleases: false
2023-10-11T00:22:37.9498502Z ##[endgroup]
2023-10-11T00:22:38.1602630Z ##[group]Installed versions
2023-10-11T00:22:38.1742015Z Successfully set up CPython (3.8.18)
2023-10-11T00:22:38.1745541Z ##[endgroup]
2023-10-11T00:22:39.2265831Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-10-11T00:22:41.4694454Z /home/runner/.cache/pip
2023-10-11T00:22:41.8322359Z Received 6245959 of 6245959 (100.0%), 44.1 MBs/sec
2023-10-11T00:22:41.8323264Z Cache Size: ~6 MB (6245959 B)
2023-10-11T00:22:41.8360303Z [command]/usr/bin/tar -xf /home/runner/work/_temp/a8548ccb-e47f-4db7-86e2-d6cec4a532de/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-10-11T00:22:41.8654485Z Cache restored successfully
2023-10-11T00:22:41.8677538Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
