2023-12-12T00:24:39.4733269Z ##[group]Run actions/setup-python@v4
2023-12-12T00:24:39.4733820Z with:
2023-12-12T00:24:39.4734139Z   python-version: 3.8
2023-12-12T00:24:39.4734524Z   architecture: x64
2023-12-12T00:24:39.4734926Z   cache: pip
2023-12-12T00:24:39.4735213Z   check-latest: false
2023-12-12T00:24:39.4735779Z   token: ***
2023-12-12T00:24:39.4736181Z   update-environment: true
2023-12-12T00:24:39.4736565Z   allow-prereleases: false
2023-12-12T00:24:39.4736907Z ##[endgroup]
2023-12-12T00:24:39.6092181Z ##[group]Installed versions
2023-12-12T00:24:39.6167938Z Successfully set up CPython (3.8.18)
2023-12-12T00:24:39.6169418Z ##[endgroup]
2023-12-12T00:24:40.5264023Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-12-12T00:24:42.4183295Z /home/runner/.cache/pip
2023-12-12T00:24:42.7766873Z Received 6245959 of 6245959 (100.0%), 35.0 MBs/sec
2023-12-12T00:24:42.7767863Z Cache Size: ~6 MB (6245959 B)
2023-12-12T00:24:42.7794905Z [command]/usr/bin/tar -xf /home/runner/work/_temp/6c44093f-0154-44bf-966f-ec880f911e4c/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-12-12T00:24:42.8070455Z Cache restored successfully
2023-12-12T00:24:42.8093166Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
