2024-01-08T00:25:10.6125879Z ##[group]Run actions/setup-python@v4
2024-01-08T00:25:10.6126429Z with:
2024-01-08T00:25:10.6126754Z   python-version: 3.8
2024-01-08T00:25:10.6127142Z   architecture: x64
2024-01-08T00:25:10.6127552Z   cache: pip
2024-01-08T00:25:10.6127848Z   check-latest: false
2024-01-08T00:25:10.6128377Z   token: ***
2024-01-08T00:25:10.6128779Z   update-environment: true
2024-01-08T00:25:10.6129164Z   allow-prereleases: false
2024-01-08T00:25:10.6129505Z ##[endgroup]
2024-01-08T00:25:10.7481307Z ##[group]Installed versions
2024-01-08T00:25:10.7558551Z Successfully set up CPython (3.8.18)
2024-01-08T00:25:10.7560098Z ##[endgroup]
2024-01-08T00:25:11.7010129Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2024-01-08T00:25:11.9986284Z /home/runner/.cache/pip
2024-01-08T00:25:12.3083075Z Received 6245959 of 6245959 (100.0%), 52.3 MBs/sec
2024-01-08T00:25:12.3084103Z Cache Size: ~6 MB (6245959 B)
2024-01-08T00:25:12.3109616Z [command]/usr/bin/tar -xf /home/runner/work/_temp/c810692f-60a6-4bd2-a488-417afd866753/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2024-01-08T00:25:12.3449820Z Cache restored successfully
2024-01-08T00:25:12.3471086Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
