2023-09-29T00:22:20.3685785Z ##[group]Run actions/setup-python@v4
2023-09-29T00:22:20.3686233Z with:
2023-09-29T00:22:20.3686558Z   python-version: 3.8
2023-09-29T00:22:20.3686847Z   architecture: x64
2023-09-29T00:22:20.3687153Z   cache: pip
2023-09-29T00:22:20.3687471Z   check-latest: false
2023-09-29T00:22:20.3688041Z   token: ***
2023-09-29T00:22:20.3688360Z   update-environment: true
2023-09-29T00:22:20.3688658Z   allow-prereleases: false
2023-09-29T00:22:20.3688986Z ##[endgroup]
2023-09-29T00:22:20.5499058Z ##[group]Installed versions
2023-09-29T00:22:20.5608008Z Successfully set up CPython (3.8.18)
2023-09-29T00:22:20.5609259Z ##[endgroup]
2023-09-29T00:22:21.3774971Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-09-29T00:22:23.4931350Z /home/runner/.cache/pip
2023-09-29T00:22:23.8898336Z Received 6245959 of 6245959 (100.0%), 35.9 MBs/sec
2023-09-29T00:22:23.8899077Z Cache Size: ~6 MB (6245959 B)
2023-09-29T00:22:23.8929979Z [command]/usr/bin/tar -xf /home/runner/work/_temp/48bc6bee-8a5d-40a1-adb1-0af972d8ffae/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-09-29T00:22:23.9309710Z Cache restored successfully
2023-09-29T00:22:23.9327157Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
