2024-01-18T00:24:39.5402666Z ##[group]Run actions/setup-python@v4
2024-01-18T00:24:39.5403250Z with:
2024-01-18T00:24:39.5403575Z   python-version: 3.8
2024-01-18T00:24:39.5403932Z   architecture: x64
2024-01-18T00:24:39.5404349Z   cache: pip
2024-01-18T00:24:39.5404674Z   check-latest: false
2024-01-18T00:24:39.5405272Z   token: ***
2024-01-18T00:24:39.5405588Z   update-environment: true
2024-01-18T00:24:39.5406220Z   allow-prereleases: false
2024-01-18T00:24:39.5406665Z ##[endgroup]
2024-01-18T00:24:39.6757780Z ##[group]Installed versions
2024-01-18T00:24:39.6831314Z Successfully set up CPython (3.8.18)
2024-01-18T00:24:39.6832828Z ##[endgroup]
2024-01-18T00:24:40.6275258Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2024-01-18T00:24:40.9600459Z /home/runner/.cache/pip
2024-01-18T00:24:41.3503597Z Received 6245959 of 6245959 (100.0%), 35.2 MBs/sec
2024-01-18T00:24:41.3504269Z Cache Size: ~6 MB (6245959 B)
2024-01-18T00:24:41.3533365Z [command]/usr/bin/tar -xf /home/runner/work/_temp/942acde0-f3d0-4145-b5a9-5129b2194771/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2024-01-18T00:24:41.3832204Z Cache restored successfully
2024-01-18T00:24:41.3855525Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
