2023-11-05T00:24:32.1301456Z ##[group]Run actions/setup-python@v4
2023-11-05T00:24:32.1301959Z with:
2023-11-05T00:24:32.1302383Z   python-version: 3.8
2023-11-05T00:24:32.1302730Z   architecture: x64
2023-11-05T00:24:32.1303167Z   cache: pip
2023-11-05T00:24:32.1303563Z   check-latest: false
2023-11-05T00:24:32.1304128Z   token: ***
2023-11-05T00:24:32.1304444Z   update-environment: true
2023-11-05T00:24:32.1304910Z   allow-prereleases: false
2023-11-05T00:24:32.1305301Z ##[endgroup]
2023-11-05T00:24:32.2674624Z ##[group]Installed versions
2023-11-05T00:24:32.2748073Z Successfully set up CPython (3.8.18)
2023-11-05T00:24:32.2749577Z ##[endgroup]
2023-11-05T00:24:33.1736652Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2023-11-05T00:24:33.5776453Z /home/runner/.cache/pip
2023-11-05T00:24:33.9011035Z Received 6245959 of 6245959 (100.0%), 41.7 MBs/sec
2023-11-05T00:24:33.9012048Z Cache Size: ~6 MB (6245959 B)
2023-11-05T00:24:33.9036663Z [command]/usr/bin/tar -xf /home/runner/work/_temp/eb54cc9d-cb39-4d29-9c97-1089998720d0/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-11-05T00:24:33.9316544Z Cache restored successfully
2023-11-05T00:24:33.9337995Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
