2023-07-17T00:31:21.7742966Z ##[group]Run actions/setup-python@v4
2023-07-17T00:31:21.7743359Z with:
2023-07-17T00:31:21.7743634Z   python-version: 3.8
2023-07-17T00:31:21.7743980Z   architecture: x64
2023-07-17T00:31:21.7744340Z   cache: pip
2023-07-17T00:31:21.7744652Z   check-latest: false
2023-07-17T00:31:21.7745098Z   token: ***
2023-07-17T00:31:21.7745431Z   update-environment: true
2023-07-17T00:31:21.7745826Z   allow-prereleases: false
2023-07-17T00:31:21.7746164Z ##[endgroup]
2023-07-17T00:31:21.9728316Z ##[group]Installed versions
2023-07-17T00:31:21.9889149Z Successfully set up CPython (3.8.17)
2023-07-17T00:31:21.9893602Z ##[endgroup]
2023-07-17T00:31:22.9578851Z [command]/opt/hostedtoolcache/Python/3.8.17/x64/bin/pip cache dir
2023-07-17T00:31:25.4753202Z /home/runner/.cache/pip
2023-07-17T00:31:25.8357476Z Received 6339595 of 6339595 (100.0%), 43.2 MBs/sec
2023-07-17T00:31:25.8358906Z Cache Size: ~6 MB (6339595 B)
2023-07-17T00:31:25.8392903Z [command]/usr/bin/tar -xf /home/runner/work/_temp/d822a7ed-191b-476d-866a-488efb21411a/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2023-07-17T00:31:25.8689796Z Cache restored successfully
2023-07-17T00:31:25.8709477Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.17-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
